name: Rsync Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: GITHUB_PUSH

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy with rsync
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          ARGS: "-avz --delete --exclude='.git*' --exclude='.env' --exclude='vendor'"
          SOURCE: "./"
          TARGET: "/var/www/admin_appsglobal"

      - name: Restart application with PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}

          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/admin_appsglobal
            composer install
            sudo chown -R apache:apache storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache
            php artisan storage:link
            php artisan config:cache
